### ISSUE TITLE
Trial key creation does not work on test example

### ISSUE THREAD

**Issue by copterspace** [Cryptolens/cryptolens-python#34]
Dear friends, I tried to test trial key creation - uncommented the last string of test.py example:

```
res = Key.create_trial_key("WyIzODQ0IiwiempTRWs4SnBKTTArYUh3WkwyZ0VwQkVyeTlUVkRWK2ZTOS8wcTBmaCJd", 3941, Helpers.GetMachineCode())
if res[0] == None or not Helpers.IsOnRightMachine(res[0]):
    print("An error occured: {0}".format(res[1]))

```

But I get an aunthentification error:
`An error occured: Unable to authenticate.`

Should this function work as it is described in readme file?

Second question: when I issue licence to my client - I specify Client name, company, email on cryptolens website, then send the license key to client. 
But if application aquires Trial license - only token and Product ID can be specified in `Key.create_trial_key`. How to specify the  Client name+company+email for the Trial Key?

**Comment by artemlos** [comment]
@copterspace Hi! The error seems to be with the access token, which no longer exist. I created a new one on my own account and it worked as expected. My recommendation is to re-create all access with your own account when testing. Then you will also be able to see how the licenses are created in the dashboard, etc.

For the second question: at the time of writing, CreateTrialKey doesn't accept customer information, email etc. The reason for it is because we designed the method to run on the client side (low trust environment), and all licenses that are generated by this method are machine specific. If you need to provide additional information in the trial key, I would recommend to use Key.CreateKey (which can also be used for trial keys since you would just need to set the "trial feature" to true). It's important though that Key.CreateKey is not run on the client side.

**Comment by copterspace** [comment]
Artem, thank you for fast reply!
I created test account, it is able to create Trial keys now.
The only issue left yet is question - how to prolong blocked Trial keys?
If I setup to automatically block expired keys in app.cryptolens.io - then after the client key is expired and blocked - I have found no way to find an appropriate key for unblocking/prolongation in app.
The Trial key is tied to Machine Code - if it is blocked in app - `create_trial_key` returns `None - This machine code has already activated the trial.`

So if user asks me to prolong trial period - I can not find appropriate key in my list. If I unblock trial key manually - `create_trial_key` returns appropriate key code - but first I need to know which key to unblock.

How to resolve if? 
For example, can you export Machine ID together with keys in `Export all keys to TSV` in the dashboard?

**Comment by artemlos** [comment]
Hi Ilya!

Sorry for a late reply.

In this case, I think the easiest is to search for the customers' machine code on the product page.

On the product page (and in the [GetKeys](https://app.cryptolens.io/docs/api/v3/getkeys) endpoint), you can search for a license with a certain machine code as follows:

For example, to find the license with machine code "DE7F9D0CDB1B68DAE79BAE2BAC478EBAB6828CB9F012503CEA30B58434C14080", we can use the following query:


> ActivatedMachines.Any(it.Mid="DE7F9D0CDB1B68DAE79BAE2BAC478EBAB6828CB9F012503CEA30B58434C14080")

This query can be entered in on the product page as shown below:

![image](https://user-images.githubusercontent.com/6392760/94789924-dcaa5580-03d5-11eb-9b6a-ceb3f78f1ffa.png)

As an example, let's suppose you have one trial user that you need to prolong. Then you would first need to ask for their machine code (which can be displayed in the application) and then query on it in the dashboard.

Please let me know if you have any questions 👍

@copterspace
