### ISSUE TITLE
models.py incorrect value format for Response.from_string

### ISSUE THREAD

**Issue by hugocarnide** [Cryptolens/cryptolens-python#61]
As per some work in progress with your library, there seems to be a strange usage on types there

in models.py, Response.from_string
```python
    result = 1
```
The conditions compare it to a string inside models and with an integer in methods.
That's confusing when using low level functions.

**Comment by artemlos** [comment]
@hugocarnide Thanks for reaching out!

I think what you are referring to is this line https://github.com/Cryptolens/cryptolens-python/blob/master/licensing/models.py#L189, where `result=1`. This is necessary in case there the result is not returned as a part of the response in rare occasions. 

In both cases, the result is treated as an integer, as far as I can tell. 

Please feel free to add more details and I can take a look at it further. I will, in meantime, close the issue, but feel free to reopen it to ask further questions or provide more feedback.

Thank you once again for submitting the issue here on GitHub!

**Comment by hugocarnide** [comment]
I understand the use cases, my concerns are that usage is not same across library as there
- https://github.com/Cryptolens/cryptolens-python/blob/master/licensing/models.py#L81
- https://github.com/Cryptolens/cryptolens-python/blob/master/licensing/methods.py#L59

**Comment by artemlos** [comment]
Thanks @hugocarnide. I see it now. I changed it in https://github.com/Cryptolens/cryptolens-python/commit/62e954361534560fa733d4b7c25378084e670973. As far as I can tell, the ValueError would never be thrown since all calls to `from_response` verify that result = 0 before calling it. However, it's good to be consistent in case a future method attempts to call `from_response` without validating whether the result is successful or not.

Thanks again!
