### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by AbdullahZafs** [Cryptolens/cryptolens-python#63]
Hello Devs, 

I hope you having a wonderful time, Can you please help me with something? I made a Discord bot and trying to add **REDEEM** feature by which users can redeem license keys and use my bot, but I'm having an issue, It keeps giving wrong responses, I attached the picture
![cryptolens](https://github.com/Cryptolens/cryptolens-python/assets/76558503/65402ae4-963b-41f6-bded-c7da62d35019)
![Capture](https://github.com/Cryptolens/cryptolens-python/assets/76558503/f970e3e9-2ed4-4545-9654-d1e6792cc8e3)

**Comment by artemlos** [comment]
@TheNightSec thanks for the question!

It's difficult to say what the error is solely by looking at the attached screenshots. A good first step is to review the error message in the api object (result of Key.activate). This will contain the detailed error message received by the server.

We have a guide on next steps depending on the issue, which is available at: https://help.cryptolens.io/faq/index#troubleshooting-api-errors

I will close this issue since it sounds like an API error not related to the Python SDK.

Please let us know if you have any questions, either here on GitHub or by emailing us at support@cryptolens.io.
